/* Ported from smartisanos.widget.DownloadProgressView in Smartisan OS 8.5.3. */
package org.opensmartisanos.ui.widget;

import android.animation.ValueAnimator;
import android.content.Context;
import android.content.res.TypedArray;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.LinearGradient;
import android.graphics.Paint;
import android.graphics.RectF;
import android.graphics.Shader;
import android.graphics.drawable.Drawable;
import android.os.Parcel;
import android.os.Parcelable;
import android.util.AttributeSet;
import android.util.TypedValue;
import android.view.View;

import org.opensmartisanos.ui.R;

public class SmartisanDownloadProgressView extends View {
    public static final int STATE_PAUSED=1,STATE_RESUMED=2,STATE_RETRY=3,STATE_PROCESSING=4;
    private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);private final Drawable download,pause,retry,processing;private int state=STATE_PAUSED,lastState=STATE_PAUSED,progress,width,alpha=255,degree;private int innerRadius,foreWidth,backWidth,foreStart,foreEnd,backStart,backEnd,failed;private long alphaDuration=300;private ValueAnimator alphaAnim;private RectF arc;
    public SmartisanDownloadProgressView(Context c){this(c,null);}public SmartisanDownloadProgressView(Context c,AttributeSet a){this(c,a,0);}public SmartisanDownloadProgressView(Context c,AttributeSet a,int s){this(c,a,s,0);}public SmartisanDownloadProgressView(Context c,AttributeSet a,int s,int r){super(c,a,s,r);TypedArray v=c.obtainStyledAttributes(a,R.styleable.SmartisanDownloadProgressView,s,r);innerRadius=v.getDimensionPixelSize(R.styleable.SmartisanDownloadProgressView_innerCircleRadius,dp(15));foreWidth=v.getDimensionPixelSize(R.styleable.SmartisanDownloadProgressView_foreRingWidth,dp(1.333f));backWidth=v.getDimensionPixelSize(R.styleable.SmartisanDownloadProgressView_backRingWidth,dp(2));progress=v.getInt(R.styleable.SmartisanDownloadProgressView_downloadProgress,0);foreStart=v.getColor(R.styleable.SmartisanDownloadProgressView_foreProgressStartColor,getColor(R.color.smartisan_rom_def_fore_progress_start_color));foreEnd=v.getColor(R.styleable.SmartisanDownloadProgressView_foreProgressEndColor,getColor(R.color.smartisan_rom_def_fore_progress_end_color));backStart=v.getColor(R.styleable.SmartisanDownloadProgressView_backProgressStartColor,getColor(R.color.smartisan_rom_def_back_progress_start_color));backEnd=v.getColor(R.styleable.SmartisanDownloadProgressView_backProgressEndColor,getColor(R.color.smartisan_rom_def_back_progress_end_color));failed=v.getColor(R.styleable.SmartisanDownloadProgressView_failedProgressColor,getColor(R.color.smartisan_rom_def_failed_progress_color));v.recycle();if(backWidth<foreWidth)throw new IllegalArgumentException("back ring must be wider than foreground ring");download=getResources().getDrawable(R.drawable.smartisan_rom_circular_progress_download);pause=getResources().getDrawable(R.drawable.smartisan_rom_circular_progress_pause);retry=getResources().getDrawable(R.drawable.smartisan_rom_circular_progress_redo);processing=getResources().getDrawable(R.drawable.smartisan_rom_circular_progress_processing);}
    private int getColor(int r){return getResources().getColor(r);}private int dp(float v){return (int)(TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP,v,getResources().getDisplayMetrics())+.9f);}public void setCurrentState(int v){if(v<1||v>4)throw new IllegalArgumentException("invalid state: "+v);if(state==v)return;lastState=state;state=v;animateAlpha();invalidate();}public int getCurrentState(){return state;}public int getLastState(){return lastState;}public void setProgress(int v){if(progress!=v){progress=v;invalidate();}}public int getProgress(){return progress;}public void setAlphaAnimationDuration(long v){alphaDuration=v;}
    @Override protected void onMeasure(int w,int h){int size=MeasureSpec.getMode(w)==MeasureSpec.EXACTLY?MeasureSpec.getSize(w):dp(36);if(size<(innerRadius+backWidth)*2)throw new IllegalArgumentException("view too small for ring");width=size;setMeasuredDimension(size,size);arc=new RectF(width/2f-innerRadius,width/2f-innerRadius,width/2f+innerRadius,width/2f+innerRadius);}
    @Override protected void onDraw(Canvas c){super.onDraw(c);int center=width/2;drawState(c,drawable(lastState),255-alpha,false,center);drawState(c,drawable(state),alpha,state==STATE_PROCESSING,center);paint.reset();paint.setAntiAlias(true);paint.setStyle(Paint.Style.STROKE);paint.setStrokeCap(Paint.Cap.ROUND);paint.setStrokeJoin(Paint.Join.ROUND);paint.setStrokeWidth(backWidth);paint.setColor(Color.parseColor("#e6e6e6"));paint.setShader(null);c.drawCircle(center,center,innerRadius,paint);paint.setStrokeWidth(foreWidth);paint.setColor(Color.parseColor("#f2f2f2"));c.drawCircle(center,center,innerRadius,paint);float sweep=progress*3.6f;paint.setStrokeWidth(backWidth);paint.setShader(state==STATE_RETRY?null:new LinearGradient(0,center-innerRadius-backWidth,0,center+innerRadius+backWidth,backStart,backEnd,Shader.TileMode.CLAMP));if(state==STATE_RETRY)paint.setColor(failed);c.drawArc(arc,-90,sweep,false,paint);paint.setStrokeWidth(foreWidth);paint.setShader(state==STATE_RETRY?null:new LinearGradient(0,center-innerRadius-foreWidth,0,center+innerRadius+foreWidth,foreStart,foreEnd,Shader.TileMode.CLAMP));if(state==STATE_RETRY)paint.setColor(failed);c.drawArc(arc,-90,sweep,false,paint);}
    private void drawState(Canvas c,Drawable d,int a,boolean rotate,int center){if(d==null||a<=0)return;int w=d.getIntrinsicWidth(),h=d.getIntrinsicHeight();d.setBounds((width-w)/2,(width-h)/2,(width+w)/2,(width+h)/2);d.setAlpha(a);if(rotate){degree=(degree+5)%360;c.save();c.rotate(degree,center,center);d.draw(c);c.restore();invalidate();}else d.draw(c);}private Drawable drawable(int v){return v==STATE_PAUSED?download:v==STATE_RESUMED?pause:v==STATE_RETRY?retry:v==STATE_PROCESSING?processing:null;}private void animateAlpha(){if(alphaDuration<=0){alpha=255;return;}if(alphaAnim!=null)alphaAnim.cancel();alphaAnim=ValueAnimator.ofInt(0,255);alphaAnim.setDuration(alphaDuration);alphaAnim.addUpdateListener(a->{alpha=(int)a.getAnimatedValue();invalidate();});alphaAnim.start();}@Override protected void onDetachedFromWindow(){if(alphaAnim!=null)alphaAnim.cancel();super.onDetachedFromWindow();}
    static class SavedState extends BaseSavedState{int progress,state;SavedState(Parcelable s){super(s);}SavedState(Parcel p){super(p);progress=p.readInt();state=p.readInt();}@Override public void writeToParcel(Parcel p,int f){super.writeToParcel(p,f);p.writeInt(progress);p.writeInt(state);}public static final Creator<SavedState> CREATOR=new Creator<SavedState>(){public SavedState createFromParcel(Parcel p){return new SavedState(p);}public SavedState[] newArray(int n){return new SavedState[n];}};}@Override public Parcelable onSaveInstanceState(){SavedState s=new SavedState(super.onSaveInstanceState());s.progress=progress;s.state=state;return s;}@Override public void onRestoreInstanceState(Parcelable p){if(!(p instanceof SavedState)){super.onRestoreInstanceState(p);return;}SavedState s=(SavedState)p;super.onRestoreInstanceState(s.getSuperState());state=s.state;lastState=s.state;progress=s.progress;invalidate();}
}
